name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y g++ premake4 zip doxygen libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev

      - name: Premake project
        run: make premake
        
      - name: Build project
        run:  make main_project
